// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: pb/account.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WalletData represents the wallet storage format
type WalletData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Accounts       []*AccountData         `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	DefaultAccount string                 `protobuf:"bytes,2,opt,name=default_account,json=defaultAccount,proto3" json:"default_account,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WalletData) Reset() {
	*x = WalletData{}
	mi := &file_pb_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletData) ProtoMessage() {}

func (x *WalletData) ProtoReflect() protoreflect.Message {
	mi := &file_pb_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletData.ProtoReflect.Descriptor instead.
func (*WalletData) Descriptor() ([]byte, []int) {
	return file_pb_account_proto_rawDescGZIP(), []int{0}
}

func (x *WalletData) GetAccounts() []*AccountData {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *WalletData) GetDefaultAccount() string {
	if x != nil {
		return x.DefaultAccount
	}
	return ""
}

func (x *WalletData) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *WalletData) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// AccountData represents individual account storage
type AccountData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	KeyFile       string                 `protobuf:"bytes,2,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"` // Path to encrypted keyfile
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountData) Reset() {
	*x = AccountData{}
	mi := &file_pb_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountData) ProtoMessage() {}

func (x *AccountData) ProtoReflect() protoreflect.Message {
	mi := &file_pb_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountData.ProtoReflect.Descriptor instead.
func (*AccountData) Descriptor() ([]byte, []int) {
	return file_pb_account_proto_rawDescGZIP(), []int{1}
}

func (x *AccountData) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AccountData) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

func (x *AccountData) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// Account represents an account with its cryptographic keys
type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PrivateKey    []byte                 `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"` // For internal use only, not for storage
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_pb_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_pb_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_pb_account_proto_rawDescGZIP(), []int{2}
}

func (x *Account) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Account) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *Account) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Account) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// EncryptedKey represents an encrypted private key file
type EncryptedKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Crypto        *CryptoKey             `protobuf:"bytes,2,opt,name=crypto,proto3" json:"crypto,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedKey) Reset() {
	*x = EncryptedKey{}
	mi := &file_pb_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedKey) ProtoMessage() {}

func (x *EncryptedKey) ProtoReflect() protoreflect.Message {
	mi := &file_pb_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedKey.ProtoReflect.Descriptor instead.
func (*EncryptedKey) Descriptor() ([]byte, []int) {
	return file_pb_account_proto_rawDescGZIP(), []int{3}
}

func (x *EncryptedKey) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *EncryptedKey) GetCrypto() *CryptoKey {
	if x != nil {
		return x.Crypto
	}
	return nil
}

func (x *EncryptedKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EncryptedKey) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *EncryptedKey) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// CryptoKey contains the encrypted private key and parameters
type CryptoKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cipher        string                 `protobuf:"bytes,1,opt,name=cipher,proto3" json:"cipher,omitempty"`
	CipherText    string                 `protobuf:"bytes,2,opt,name=cipher_text,json=cipherText,proto3" json:"cipher_text,omitempty"`
	CipherParams  *CipherParams          `protobuf:"bytes,3,opt,name=cipher_params,json=cipherParams,proto3" json:"cipher_params,omitempty"`
	Kdf           string                 `protobuf:"bytes,4,opt,name=kdf,proto3" json:"kdf,omitempty"`
	KdfParams     *KDFParams             `protobuf:"bytes,5,opt,name=kdf_params,json=kdfParams,proto3" json:"kdf_params,omitempty"`
	Mac           string                 `protobuf:"bytes,6,opt,name=mac,proto3" json:"mac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoKey) Reset() {
	*x = CryptoKey{}
	mi := &file_pb_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoKey) ProtoMessage() {}

func (x *CryptoKey) ProtoReflect() protoreflect.Message {
	mi := &file_pb_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoKey.ProtoReflect.Descriptor instead.
func (*CryptoKey) Descriptor() ([]byte, []int) {
	return file_pb_account_proto_rawDescGZIP(), []int{4}
}

func (x *CryptoKey) GetCipher() string {
	if x != nil {
		return x.Cipher
	}
	return ""
}

func (x *CryptoKey) GetCipherText() string {
	if x != nil {
		return x.CipherText
	}
	return ""
}

func (x *CryptoKey) GetCipherParams() *CipherParams {
	if x != nil {
		return x.CipherParams
	}
	return nil
}

func (x *CryptoKey) GetKdf() string {
	if x != nil {
		return x.Kdf
	}
	return ""
}

func (x *CryptoKey) GetKdfParams() *KDFParams {
	if x != nil {
		return x.KdfParams
	}
	return nil
}

func (x *CryptoKey) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

// CipherParams contains cipher parameters
type CipherParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Iv            string                 `protobuf:"bytes,1,opt,name=iv,proto3" json:"iv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CipherParams) Reset() {
	*x = CipherParams{}
	mi := &file_pb_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CipherParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CipherParams) ProtoMessage() {}

func (x *CipherParams) ProtoReflect() protoreflect.Message {
	mi := &file_pb_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CipherParams.ProtoReflect.Descriptor instead.
func (*CipherParams) Descriptor() ([]byte, []int) {
	return file_pb_account_proto_rawDescGZIP(), []int{5}
}

func (x *CipherParams) GetIv() string {
	if x != nil {
		return x.Iv
	}
	return ""
}

// KDFParams contains key derivation function parameters
type KDFParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dklen         int32                  `protobuf:"varint,1,opt,name=dklen,proto3" json:"dklen,omitempty"`
	N             int32                  `protobuf:"varint,2,opt,name=n,proto3" json:"n,omitempty"`
	P             int32                  `protobuf:"varint,3,opt,name=p,proto3" json:"p,omitempty"`
	R             int32                  `protobuf:"varint,4,opt,name=r,proto3" json:"r,omitempty"`
	Salt          string                 `protobuf:"bytes,5,opt,name=salt,proto3" json:"salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KDFParams) Reset() {
	*x = KDFParams{}
	mi := &file_pb_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KDFParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KDFParams) ProtoMessage() {}

func (x *KDFParams) ProtoReflect() protoreflect.Message {
	mi := &file_pb_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KDFParams.ProtoReflect.Descriptor instead.
func (*KDFParams) Descriptor() ([]byte, []int) {
	return file_pb_account_proto_rawDescGZIP(), []int{6}
}

func (x *KDFParams) GetDklen() int32 {
	if x != nil {
		return x.Dklen
	}
	return 0
}

func (x *KDFParams) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *KDFParams) GetP() int32 {
	if x != nil {
		return x.P
	}
	return 0
}

func (x *KDFParams) GetR() int32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *KDFParams) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

var File_pb_account_proto protoreflect.FileDescriptor

const file_pb_account_proto_rawDesc = "" +
	"\n" +
	"\x10pb/account.proto\x12\x02pb\"\xa0\x01\n" +
	"\n" +
	"WalletData\x12+\n" +
	"\baccounts\x18\x01 \x03(\v2\x0f.pb.AccountDataR\baccounts\x12'\n" +
	"\x0fdefault_account\x18\x02 \x01(\tR\x0edefaultAccount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\x03R\tupdatedAt\"a\n" +
	"\vAccountData\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x19\n" +
	"\bkey_file\x18\x02 \x01(\tR\akeyFile\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"\x82\x01\n" +
	"\aAccount\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1f\n" +
	"\vprivate_key\x18\x02 \x01(\fR\n" +
	"privateKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"\x97\x01\n" +
	"\fEncryptedKey\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12%\n" +
	"\x06crypto\x18\x02 \x01(\v2\r.pb.CryptoKeyR\x06crypto\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\xcd\x01\n" +
	"\tCryptoKey\x12\x16\n" +
	"\x06cipher\x18\x01 \x01(\tR\x06cipher\x12\x1f\n" +
	"\vcipher_text\x18\x02 \x01(\tR\n" +
	"cipherText\x125\n" +
	"\rcipher_params\x18\x03 \x01(\v2\x10.pb.CipherParamsR\fcipherParams\x12\x10\n" +
	"\x03kdf\x18\x04 \x01(\tR\x03kdf\x12,\n" +
	"\n" +
	"kdf_params\x18\x05 \x01(\v2\r.pb.KDFParamsR\tkdfParams\x12\x10\n" +
	"\x03mac\x18\x06 \x01(\tR\x03mac\"\x1e\n" +
	"\fCipherParams\x12\x0e\n" +
	"\x02iv\x18\x01 \x01(\tR\x02iv\"_\n" +
	"\tKDFParams\x12\x14\n" +
	"\x05dklen\x18\x01 \x01(\x05R\x05dklen\x12\f\n" +
	"\x01n\x18\x02 \x01(\x05R\x01n\x12\f\n" +
	"\x01p\x18\x03 \x01(\x05R\x01p\x12\f\n" +
	"\x01r\x18\x04 \x01(\x05R\x01r\x12\x12\n" +
	"\x04salt\x18\x05 \x01(\tR\x04saltB\x1dZ\x1bgithub.com/torcnet/torcnet/pbb\x06proto3"

var (
	file_pb_account_proto_rawDescOnce sync.Once
	file_pb_account_proto_rawDescData []byte
)

func file_pb_account_proto_rawDescGZIP() []byte {
	file_pb_account_proto_rawDescOnce.Do(func() {
		file_pb_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_account_proto_rawDesc), len(file_pb_account_proto_rawDesc)))
	})
	return file_pb_account_proto_rawDescData
}

var file_pb_account_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pb_account_proto_goTypes = []any{
	(*WalletData)(nil),   // 0: pb.WalletData
	(*AccountData)(nil),  // 1: pb.AccountData
	(*Account)(nil),      // 2: pb.Account
	(*EncryptedKey)(nil), // 3: pb.EncryptedKey
	(*CryptoKey)(nil),    // 4: pb.CryptoKey
	(*CipherParams)(nil), // 5: pb.CipherParams
	(*KDFParams)(nil),    // 6: pb.KDFParams
}
var file_pb_account_proto_depIdxs = []int32{
	1, // 0: pb.WalletData.accounts:type_name -> pb.AccountData
	4, // 1: pb.EncryptedKey.crypto:type_name -> pb.CryptoKey
	5, // 2: pb.CryptoKey.cipher_params:type_name -> pb.CipherParams
	6, // 3: pb.CryptoKey.kdf_params:type_name -> pb.KDFParams
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pb_account_proto_init() }
func file_pb_account_proto_init() {
	if File_pb_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_account_proto_rawDesc), len(file_pb_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_account_proto_goTypes,
		DependencyIndexes: file_pb_account_proto_depIdxs,
		MessageInfos:      file_pb_account_proto_msgTypes,
	}.Build()
	File_pb_account_proto = out.File
	file_pb_account_proto_goTypes = nil
	file_pb_account_proto_depIdxs = nil
}
