// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: pb/state.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Account represents an account in the blockchain state
type StateAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance       uint64                 `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Nonce         uint64                 `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Code          []byte                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Storage       map[string][]byte      `protobuf:"bytes,5,rep,name=storage,proto3" json:"storage,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateAccount) Reset() {
	*x = StateAccount{}
	mi := &file_pb_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateAccount) ProtoMessage() {}

func (x *StateAccount) ProtoReflect() protoreflect.Message {
	mi := &file_pb_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateAccount.ProtoReflect.Descriptor instead.
func (*StateAccount) Descriptor() ([]byte, []int) {
	return file_pb_state_proto_rawDescGZIP(), []int{0}
}

func (x *StateAccount) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *StateAccount) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *StateAccount) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *StateAccount) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *StateAccount) GetStorage() map[string][]byte {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *StateAccount) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *StateAccount) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// AccountDiff represents changes to an account
type AccountDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	OldBalance    uint64                 `protobuf:"varint,2,opt,name=old_balance,json=oldBalance,proto3" json:"old_balance,omitempty"`
	NewBalance    uint64                 `protobuf:"varint,3,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	OldNonce      uint64                 `protobuf:"varint,4,opt,name=old_nonce,json=oldNonce,proto3" json:"old_nonce,omitempty"`
	NewNonce      uint64                 `protobuf:"varint,5,opt,name=new_nonce,json=newNonce,proto3" json:"new_nonce,omitempty"`
	OldCode       []byte                 `protobuf:"bytes,6,opt,name=old_code,json=oldCode,proto3" json:"old_code,omitempty"`
	NewCode       []byte                 `protobuf:"bytes,7,opt,name=new_code,json=newCode,proto3" json:"new_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountDiff) Reset() {
	*x = AccountDiff{}
	mi := &file_pb_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountDiff) ProtoMessage() {}

func (x *AccountDiff) ProtoReflect() protoreflect.Message {
	mi := &file_pb_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountDiff.ProtoReflect.Descriptor instead.
func (*AccountDiff) Descriptor() ([]byte, []int) {
	return file_pb_state_proto_rawDescGZIP(), []int{1}
}

func (x *AccountDiff) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AccountDiff) GetOldBalance() uint64 {
	if x != nil {
		return x.OldBalance
	}
	return 0
}

func (x *AccountDiff) GetNewBalance() uint64 {
	if x != nil {
		return x.NewBalance
	}
	return 0
}

func (x *AccountDiff) GetOldNonce() uint64 {
	if x != nil {
		return x.OldNonce
	}
	return 0
}

func (x *AccountDiff) GetNewNonce() uint64 {
	if x != nil {
		return x.NewNonce
	}
	return 0
}

func (x *AccountDiff) GetOldCode() []byte {
	if x != nil {
		return x.OldCode
	}
	return nil
}

func (x *AccountDiff) GetNewCode() []byte {
	if x != nil {
		return x.NewCode
	}
	return nil
}

// StorageDiff represents changes to account storage
type StorageDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	OldValue      []byte                 `protobuf:"bytes,3,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue      []byte                 `protobuf:"bytes,4,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageDiff) Reset() {
	*x = StorageDiff{}
	mi := &file_pb_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageDiff) ProtoMessage() {}

func (x *StorageDiff) ProtoReflect() protoreflect.Message {
	mi := &file_pb_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageDiff.ProtoReflect.Descriptor instead.
func (*StorageDiff) Descriptor() ([]byte, []int) {
	return file_pb_state_proto_rawDescGZIP(), []int{2}
}

func (x *StorageDiff) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *StorageDiff) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StorageDiff) GetOldValue() []byte {
	if x != nil {
		return x.OldValue
	}
	return nil
}

func (x *StorageDiff) GetNewValue() []byte {
	if x != nil {
		return x.NewValue
	}
	return nil
}

// StateSnapshot represents a snapshot of the blockchain state
type StateSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*StateAccount        `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	AccountDiffs  []*AccountDiff         `protobuf:"bytes,2,rep,name=account_diffs,json=accountDiffs,proto3" json:"account_diffs,omitempty"`
	StorageDiffs  []*StorageDiff         `protobuf:"bytes,3,rep,name=storage_diffs,json=storageDiffs,proto3" json:"storage_diffs,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,5,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateSnapshot) Reset() {
	*x = StateSnapshot{}
	mi := &file_pb_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSnapshot) ProtoMessage() {}

func (x *StateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_pb_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSnapshot.ProtoReflect.Descriptor instead.
func (*StateSnapshot) Descriptor() ([]byte, []int) {
	return file_pb_state_proto_rawDescGZIP(), []int{3}
}

func (x *StateSnapshot) GetAccounts() []*StateAccount {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *StateSnapshot) GetAccountDiffs() []*AccountDiff {
	if x != nil {
		return x.AccountDiffs
	}
	return nil
}

func (x *StateSnapshot) GetStorageDiffs() []*StorageDiff {
	if x != nil {
		return x.StorageDiffs
	}
	return nil
}

func (x *StateSnapshot) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StateSnapshot) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

var File_pb_state_proto protoreflect.FileDescriptor

const file_pb_state_proto_rawDesc = "" +
	"\n" +
	"\x0epb/state.proto\x12\x02pb\"\x9f\x02\n" +
	"\fStateAccount\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x04R\abalance\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\x04R\x05nonce\x12\x12\n" +
	"\x04code\x18\x04 \x01(\fR\x04code\x127\n" +
	"\astorage\x18\x05 \x03(\v2\x1d.pb.StateAccount.StorageEntryR\astorage\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\x1a:\n" +
	"\fStorageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xd9\x01\n" +
	"\vAccountDiff\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1f\n" +
	"\vold_balance\x18\x02 \x01(\x04R\n" +
	"oldBalance\x12\x1f\n" +
	"\vnew_balance\x18\x03 \x01(\x04R\n" +
	"newBalance\x12\x1b\n" +
	"\told_nonce\x18\x04 \x01(\x04R\boldNonce\x12\x1b\n" +
	"\tnew_nonce\x18\x05 \x01(\x04R\bnewNonce\x12\x19\n" +
	"\bold_code\x18\x06 \x01(\fR\aoldCode\x12\x19\n" +
	"\bnew_code\x18\a \x01(\fR\anewCode\"s\n" +
	"\vStorageDiff\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1b\n" +
	"\told_value\x18\x03 \x01(\fR\boldValue\x12\x1b\n" +
	"\tnew_value\x18\x04 \x01(\fR\bnewValue\"\xea\x01\n" +
	"\rStateSnapshot\x12,\n" +
	"\baccounts\x18\x01 \x03(\v2\x10.pb.StateAccountR\baccounts\x124\n" +
	"\raccount_diffs\x18\x02 \x03(\v2\x0f.pb.AccountDiffR\faccountDiffs\x124\n" +
	"\rstorage_diffs\x18\x03 \x03(\v2\x0f.pb.StorageDiffR\fstorageDiffs\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12!\n" +
	"\fblock_number\x18\x05 \x01(\x04R\vblockNumberB\x1dZ\x1bgithub.com/torcnet/torcnet/pbb\x06proto3"

var (
	file_pb_state_proto_rawDescOnce sync.Once
	file_pb_state_proto_rawDescData []byte
)

func file_pb_state_proto_rawDescGZIP() []byte {
	file_pb_state_proto_rawDescOnce.Do(func() {
		file_pb_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_state_proto_rawDesc), len(file_pb_state_proto_rawDesc)))
	})
	return file_pb_state_proto_rawDescData
}

var file_pb_state_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_state_proto_goTypes = []any{
	(*StateAccount)(nil),  // 0: pb.StateAccount
	(*AccountDiff)(nil),   // 1: pb.AccountDiff
	(*StorageDiff)(nil),   // 2: pb.StorageDiff
	(*StateSnapshot)(nil), // 3: pb.StateSnapshot
	nil,                   // 4: pb.StateAccount.StorageEntry
}
var file_pb_state_proto_depIdxs = []int32{
	4, // 0: pb.StateAccount.storage:type_name -> pb.StateAccount.StorageEntry
	0, // 1: pb.StateSnapshot.accounts:type_name -> pb.StateAccount
	1, // 2: pb.StateSnapshot.account_diffs:type_name -> pb.AccountDiff
	2, // 3: pb.StateSnapshot.storage_diffs:type_name -> pb.StorageDiff
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pb_state_proto_init() }
func file_pb_state_proto_init() {
	if File_pb_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_state_proto_rawDesc), len(file_pb_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_state_proto_goTypes,
		DependencyIndexes: file_pb_state_proto_depIdxs,
		MessageInfos:      file_pb_state_proto_msgTypes,
	}.Build()
	File_pb_state_proto = out.File
	file_pb_state_proto_goTypes = nil
	file_pb_state_proto_depIdxs = nil
}
